---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 20/03/22 23:00
---


-- @param insert {function(tableName : string, object : table) string}
-- @return {table}
function newInstance(insert, delete)
    return {
        insert = insert,
        delete = delete
    }
end



return {
    newInstance = newInstance
}