---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 20/03/22 23:00
---


-- @param select {function(tableName : string, object : table, columns : table) string}
-- @param insert {function(tableName : string, object : table) string}
-- @param delete {function(tableName : string, object : table) string}
-- @return {table} Instance of IBuilder
function newInstance(select, insert, delete)
    return {
        select = select,
        insert = insert,
        delete = delete
    }
end



return {
    newInstance = newInstance
}