---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 20/03/22 22:10
---

-- Object constructor of SqlParser. Use this object to parse SQL request (Object to SQL)
function SqlBuilder(tableName)
    local this = {}

    this.insert = function(object)
        print(tableName .. " insert :")
        for column, value in pairs(object) do
            print(column, value)
        end
    end

    return this;
end


return SqlBuilder