---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 20/03/22 23:41
---


function StringJoiner(prefix, delimiter, suffix)
    local this = {}

    delimiter = (delimiter or "")
    local str = prefix or ""
    local size = 0

    -- Append value to current str
    this.append = function(newStr)
        if size > 0 then
            str = str .. (delimiter or "") .. newStr
        else
            str = str .. newStr
        end

        size = size + 1
    end

    -- Return result of joining
    this.toString = function()
        return str .. suffix
    end

    -- Return joiner size
    this.getSize = function()
        return size
    end

    return this
end



return StringJoiner

