---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 20/03/22 23:41
---


function StringJoiner(prefix, delimiter, suffix)
    local this = {}

    delimiter = (delimiter or "")
    local str = prefix or ""
    local hasAppend = false

    -- Append value to current str
    this.append = function(newStr)
        if hasAppend then
            str = str .. (delimiter or "") .. newStr
        else
            str = str .. newStr
            hasAppend = true
        end
    end

    -- Return result of joining
    this.toString = function()
        return str .. suffix
    end

    return this
end



return StringJoiner

