---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 20/03/22 23:00
---

local IBuilder = require("modules/SqlBuilder/IBuilder")
local StringJoiner = require("modules/SqlBuilder/StringJoiner")


local MysqlBuilder = function()

    -- insert {function(object : table) string}
    -- @param tableName {string} Name of database table
    local function insert(tableName, object)
        local keyJoiner = StringJoiner("(", ", ", ")")
        local valueJoiner = StringJoiner("(", ", ", ")")

        for column, value in pairs(object) do
            keyJoiner.append(column)
            valueJoiner.append(value)
        end
        print("osdf","INSERT INTO " .. tableName .. " " .. keyJoiner.toString() .. " VALUES " .. valueJoiner.toString())

        return "INSERT INTO " .. tableName .. " " .. keyJoiner.toString() .. " VALUES " .. valueJoiner.toString()
    end


    return IBuilder.newInstance(insert)
end



return MysqlBuilder